# Generated by Django 4.0.2 on 2022-02-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='alignment',
            field=models.CharField(choices=[('LG', 'Lawful Good'), ('NG', 'Neutral Good'), ('CG', 'Chaotic Good')], default='Chaotic Good', max_length=2),
        ),
        migrations.AddField(
            model_name='sheet',
            name='classes',
            field=models.CharField(choices=[('FIG', 'Fighter'), ('WIZ', 'Wizard'), ('CLE', 'Cleric')], default='Fighter', max_length=20),
        ),
    ]
