# Generated by Django 4.0.2 on 2022-03-03 07:17

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0007_sheet_cha_sheet_con_sheet_dex_sheet_int_sheet_str_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='AC',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sheet',
            name='current',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='sheet',
            name='exp',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20),
                                                             django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='sheet',
            name='hitDice',
            field=models.CharField(choices=[('d4', 'd4'), ('d6', 'd6'), ('d8', 'd8'), ('d10', 'd10'), ('d12', 'd12')],
                                   default='d6', max_length=3),
        ),
        migrations.AddField(
            model_name='sheet',
            name='initiation',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sheet',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='maxHp',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sheet',
            name='numHitDice',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sheet',
            name='proficiencies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='savThrow',
            field=multiselectfield.db.fields.MultiSelectField(blank=True,
                                                              choices=[('Str', 'Strength'), ('Dex', 'Dexterity'),
                                                                       ('Con', 'Constitution'), ('Int', 'Intelligence'),
                                                                       ('Wis', 'Wisdom'), ('Cha', 'Charisma')],
                                                              max_length=23),
        ),
        migrations.AddField(
            model_name='sheet',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Acrobatics', 'Acrobatics (Dex)'), (
            'Animal Handling', 'Animal Handling (Wis)'), ('Arcana', 'Arcana (Int)'), ('Athletics', 'Athletics (Str)'),
                                                                                   ('Deception', 'Deception (Cha)'),
                                                                                   ('History', 'History (Int)'),
                                                                                   ('Insight', 'Insight (Wis)'), (
                                                                                   'Intimidation',
                                                                                   'Intimidation (Cha)'), (
                                                                                   'Investigation',
                                                                                   'Investigation (Int)'),
                                                                                   ('Medicine', 'Medicine (Wis)'),
                                                                                   ('Nature', 'Nature (Wis)'),
                                                                                   ('Perception', 'Perception (Wis)'),
                                                                                   ('Performance', 'Performance (Cha)'),
                                                                                   ('Persuasion', 'Persuasion (Cha)'),
                                                                                   ('Religion', 'Religion (Int)'), (
                                                                                   'Sleight of Hand',
                                                                                   'Sleight of Hand (Dex)'),
                                                                                   ('Stealth', 'Stealth (Dex)'),
                                                                                   ('Survival', 'Survival (Wis)')],
                                                              max_length=188),
        ),
        migrations.AddField(
            model_name='sheet',
            name='speed',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sheet',
            name='tempHp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='classes',
            field=models.CharField(choices=[('FIGHTER', 'Fighter'), ('BARBARIAN', 'Barbarian'), ('ROGUE', 'Rogue')],
                                   default='Fighter', max_length=20),
        ),
    ]
