# Generated by Django 4.0.2 on 2022-03-03 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0008_sheet_ac_sheet_current_sheet_exp_sheet_hitdice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='savThrow',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='skills',
        ),
    ]
