# Generated by Django 4.0.2 on 2022-03-03 07:29

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0009_remove_sheet_savthrow_remove_sheet_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='race',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='savThrow',
            field=multiselectfield.db.fields.MultiSelectField(blank=True,
                                                              choices=[('Str', 'Strength'), ('Dex', 'Dexterity'),
                                                                       ('Con', 'Constitution'), ('Int', 'Intelligence'),
                                                                       ('Wis', 'Wisdom'), ('Cha', 'Charisma')],
                                                              default='Str', max_length=23),
        ),
        migrations.AddField(
            model_name='sheet',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[('Acrobatics', 'Acrobatics (Dex)'), ('Animal Handling', 'Animal Handling (Wis)'),
                         ('Arcana', 'Arcana (Int)'), ('Athletics', 'Athletics (Str)'), ('Deception', 'Deception (Cha)'),
                         ('History', 'History (Int)'), ('Insight', 'Insight (Wis)'),
                         ('Intimidation', 'Intimidation (Cha)'), ('Investigation', 'Investigation (Int)'),
                         ('Medicine', 'Medicine (Wis)'), ('Nature', 'Nature (Wis)'), ('Perception', 'Perception (Wis)'),
                         ('Performance', 'Performance (Cha)'), ('Persuasion', 'Persuasion (Cha)'),
                         ('Religion', 'Religion (Int)'), ('Sleight of Hand', 'Sleight of Hand (Dex)'),
                         ('Stealth', 'Stealth (Dex)'), ('Survival', 'Survival (Wis)')], default='Acrobatics',
                max_length=188),
        ),
    ]
