# Generated by Django 4.0.2 on 2022-03-03 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0010_sheet_background_sheet_race_sheet_savthrow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='AC',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='initiation',
        ),
        migrations.AddField(
            model_name='sheet',
            name='armourAC',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sheet',
            name='bonds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='flaws',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='ideals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='initiationRoll',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sheet',
            name='personality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='background',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='race',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
