# Generated by Django 4.0.2 on 2022-03-03 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0011_remove_sheet_ac_remove_sheet_initiation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='description',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='sheet',
            name='cp',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sheet',
            name='gp',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sheet',
            name='inspiration',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sheet',
            name='pp',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sheet',
            name='sp',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
