# Generated by Django 4.0.2 on 2022-03-03 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0012_rename_description_sheet_notes_sheet_cp_sheet_gp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='currentHitDice',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='classes',
            field=models.CharField(choices=[('Fighter', 'Fighter'), ('Barbarian', 'Barbarian'), ('Rogue', 'Rogue')],
                                   default='Fighter', max_length=20),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='cp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='exp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='gp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='pp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
