# Generated by Django 4.0.2 on 2022-03-03 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0013_sheet_currenthitdice_alter_sheet_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='deathFail',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3),
                                                             django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sheet',
            name='deathSuccess',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3),
                                                             django.core.validators.MinValueValidator(0)]),
        ),
    ]
