# Generated by Django 4.0.2 on 2022-03-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0014_sheet_deathfail_sheet_deathsuccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='equipment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='spells',
            field=models.TextField(blank=True, null=True),
        ),
    ]
