# Generated by Django 4.0.2 on 2022-03-10 02:40

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0015_sheet_equipment_sheet_features_sheet_spells'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='alignment',
            field=models.CharField(choices=[('Lawful Good', 'Lawful Good'), ('Neutral Good', 'Neutral Good'),
                                            ('Chaotic Good', 'Chaotic Good'), ('Lawful Neutral', 'Lawful Neutral'),
                                            ('True Neutral', 'True Neutral'), ('Chaotic Neutral', 'Chaotic Neutral'),
                                            ('Lawful Evil', 'Lawful Evil'), ('Neutral Evil', 'Neutral Evil'),
                                            ('Chaotic Evil', 'Chaotic Evil')], default='Chaotic Good', max_length=20),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='inspiration',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='savThrow',
            field=multiselectfield.db.fields.MultiSelectField(blank=True,
                                                              choices=[('Str', 'Strength'), ('Dex', 'Dexterity'),
                                                                       ('Con', 'Constitution'), ('Int', 'Intelligence'),
                                                                       ('Wis', 'Wisdom'), ('Cha', 'Charisma')],
                                                              max_length=23),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Acrobatics', 'Acrobatics (Dex)'), (
            'Animal Handling', 'Animal Handling (Wis)'), ('Arcana', 'Arcana (Int)'), ('Athletics', 'Athletics (Str)'),
                                                                                   ('Deception', 'Deception (Cha)'),
                                                                                   ('History', 'History (Int)'),
                                                                                   ('Insight', 'Insight (Wis)'), (
                                                                                   'Intimidation',
                                                                                   'Intimidation (Cha)'), (
                                                                                   'Investigation',
                                                                                   'Investigation (Int)'),
                                                                                   ('Medicine', 'Medicine (Wis)'),
                                                                                   ('Nature', 'Nature (Wis)'),
                                                                                   ('Perception', 'Perception (Wis)'),
                                                                                   ('Performance', 'Performance (Cha)'),
                                                                                   ('Persuasion', 'Persuasion (Cha)'),
                                                                                   ('Religion', 'Religion (Int)'), (
                                                                                   'Sleight of Hand',
                                                                                   'Sleight of Hand (Dex)'),
                                                                                   ('Stealth', 'Stealth (Dex)'),
                                                                                   ('Survival', 'Survival (Wis)')],
                                                              max_length=188),
        ),
    ]
