# Generated by Django 4.0.2 on 2022-03-25 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0016_feat_rating_alter_sheet_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='score',
        ),
        migrations.AddField(
            model_name='rating',
            name='feat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feat_rating',
                                    to='base.feat', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='fun',
            field=models.IntegerField(
                choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='usefulness',
            field=models.IntegerField(
                choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rating',
                                    to=settings.AUTH_USER_MODEL, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feat',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
