# Generated by Django 4.0.2 on 2022-03-10 06:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0016_alter_sheet_alignment_alter_sheet_inspiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='savThrow',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Strength', 'Strength_'),
                                                                                   ('Dexterity', 'Dexterity_'),
                                                                                   ('Constitution', 'Constitution_'),
                                                                                   ('Intelligence', 'Intelligence_'),
                                                                                   ('Wisdom', 'Wisdom_'),
                                                                                   ('Charisma', 'Charisma_')],
                                                              max_length=60),
        ),
    ]
