# Generated by Django 4.0.2 on 2022-03-25 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0017_remove_rating_score_rating_feat_rating_fun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='feat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.feat'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
