# Generated by Django 4.0.2 on 2022-03-25 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0018_alter_rating_feat_alter_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='numberOfRatings',
        ),
    ]
