# Generated by Django 4.0.2 on 2022-03-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0019_remove_rating_numberofratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='feats',
            field=models.ManyToManyField(blank=True, to='base.Feat'),
        ),
    ]
