# Generated by Django 4.0.2 on 2022-03-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0020_sheet_feats'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rating',
            name='fun',
            field=models.IntegerField(
                choices=[(1, '1 - Trash'), (2, '2 - Bad'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Amazing')]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='usefulness',
            field=models.IntegerField(
                choices=[(1, '1 - Trash'), (2, '2 - Bad'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Amazing')]),
        ),
    ]
