# Generated by Django 4.0.2 on 2022-03-25 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0021_rating_comment_alter_rating_fun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feat',
            name='numberRatings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='feat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feat_rating',
                                    to='base.feat'),
        ),
    ]
